function hsv(r,g,b){r/=255;g/=255;b/=255;const m=Math.max(r,g,b),n=Math.min(r,g,b),d=m-n;let h=0;if(d){if(m===r)h=((g-b)/d)%6;else if(m===g)h=(b-r)/d+2;else h=(r-g)/d+4;h*=60;if(h<0)h+=360}return{h,s:m?d/m:0,v:m}}
function median(a){if(!a.length)return 255;const b=a.slice().sort((x,y)=>x-y);return b[b.length>>1]}
function otsu(vals){const h=new Array(256).fill(0);for(const v of vals)h[Math.max(0,Math.min(255,v|0))]++;const n=vals.length;let sum=0;for(let i=0;i<256;i++)sum+=i*h[i];let wB=0,sumB=0,best=0,thr=80;for(let t=0;t<256;t++){wB+=h[t];if(!wB)continue;const wF=n-wB;if(!wF)break;sumB+=t*h[t];const mB=sumB/wB,mF=(sum-sumB)/wF,sc=wB*wF*(mB-mF)*(mB-mF);if(sc>best){best=sc;thr=t}}return thr}
function renderCrack(){
view.innerHTML=`<h2>From clues</h2><p class="lead">Hunt a Bedrock seed from structure positions. Photo analysis is on the Photo tab.</p><div class="card"><h3>Bedrock seed from structures</h3><p class="note">Add each structure and its block X/Z.</p><div id="known"></div><button class="secondary" id="addk">+ structure clue</button><div class="row" style="margin-top:10px"><label class="field">Tolerance<input id="tol" type="number" value="${state.tol}"></label><label class="field">Seeds to try<input id="kc" type="number" value="${state.seedCount}"></label><label class="field">Workers<input id="kw" type="number" value="${state.workers}"></label><button id="kgo">Find seed</button><button class="danger" id="kstop">Stop</button></div><div id="kstats"></div><table><thead><tr><th>Seed</th></tr></thead><tbody id="krows"></tbody></table></div>`;
paintKnown();paintKResults();
document.getElementById("addk").onclick=()=>{state.known.push({id:"village",x:0,z:0});paintKnown()};
document.getElementById("kgo").onclick=()=>{state.tol=Math.max(4,+document.getElementById("tol").value||24);state.seedCount=Math.max(1,Math.min(1e9,+document.getElementById("kc").value||1));state.workers=Math.max(1,Math.min(16,+document.getElementById("kw").value||1));runCrack()};
document.getElementById("kstop").onclick=stopSearch;
}
function renderPhoto(){
if(!state.gridN)state.gridN=8;if(state.thr==null)state.thr=0;if(!state.pmode)state.pmode="auto";if(!state.pedition)state.pedition="bedrock";
const be=state.pedition==="bedrock";
view.innerHTML=`<h2>Photo analysis</h2><p class="lead">Works for Bedrock and Java pictures. Pick a pickup mode, then read the photo.</p><div class="card row"><button class="${be?"":"secondary"}" id="peBE">Bedrock photo</button><button class="${be?"secondary":""}" id="peJE">Java photo</button></div><div class="card"><label class="field">Pickup mode<select id="pmode"><option value="auto">Auto colour</option><option value="dark">Dark blocks</option><option value="deepslate">Deepslate</option><option value="bamboo">Bamboo / leaves</option><option value="clouds">Clouds</option><option value="rotation" ${be?"disabled":""}>Texture rotation (Java)</option><option value="bedrock" ${be?"disabled":""}>Bedrock floor (Java)</option></select></label>${be?"":"<label class=field>Java world seed<input id=pseed value='"+(state.patSeed||"0")+"'></label>"}<label class="field">Photo<input id="pic" type="file" accept="image/*"></label><canvas id="pcv" width="520" height="340" style="width:100%;max-width:520px;background:#0003;border-radius:8px"></canvas><div class="row"><label class="field">Grid<input id="gsz" type="number" min="4" max="16" value="${state.gridN}"></label><label class="field">Sensitivity 0=auto<input id="thr" type="number" min="0" max="200" value="${state.thr}"></label><label class="field">Y<input id="py" type="number" value="${state.patY||-64}"></label></div><div class="row"><button id="pan">Read photo</button><button class="secondary" id="pinv">Invert</button><button class="secondary" id="pclr">Clear</button><button id="pgo">Search</button></div><p class="note" id="pread">Crop to a flat wall or floor.</p><div class="grid8" id="pg" style="margin-top:8px"></div><div id="pout" class="note"></div></div>`;
if(be&&(state.pmode==="rotation"||state.pmode==="bedrock"))state.pmode="auto";
document.getElementById("pmode").value=state.pmode;
paintGrid();if(state.photo){drawPhoto();analyzePhoto()}
document.getElementById("peBE").onclick=()=>{state.pedition="bedrock";renderPhoto()};
document.getElementById("peJE").onclick=()=>{state.pedition="java";renderPhoto()};
const seedEl=document.getElementById("pseed");if(seedEl)seedEl.oninput=e=>state.patSeed=e.target.value;
document.getElementById("py").oninput=e=>state.patY=+e.target.value||-64;
document.getElementById("pmode").onchange=e=>{state.pmode=e.target.value;if(state.photo)analyzePhoto();else paintGrid()};
document.getElementById("gsz").oninput=e=>{state.gridN=Math.max(4,Math.min(16,+e.target.value||8));state.pat=Array(state.gridN*state.gridN).fill(0);state.rots=Array(state.gridN*state.gridN).fill(-1);if(state.photo){drawPhoto();analyzePhoto()}else paintGrid()};
document.getElementById("thr").oninput=e=>state.thr=+e.target.value||0;
document.getElementById("pic").onchange=onPhoto;
document.getElementById("pan").onclick=analyzePhoto;
document.getElementById("pinv").onclick=()=>{if(state.pat)state.pat=state.pat.map(v=>v?0:1);paintGrid();if(state.photo)drawPhoto()};
document.getElementById("pclr").onclick=()=>{const n=(state.gridN||8)**2;state.pat=Array(n).fill(0);state.rots=Array(n).fill(-1);paintGrid()};
document.getElementById("pgo").onclick=searchPattern;
}
function onPhoto(e){const f=e.target.files&&e.target.files[0];if(!f)return;const img=new Image();img.onload=()=>{state.photo=img;drawPhoto();analyzePhoto()};img.src=URL.createObjectURL(f)}
function drawPhoto(){const c=document.getElementById("pcv");if(!c||!state.photo)return;const x=c.getContext("2d"),n=state.gridN||8;x.clearRect(0,0,c.width,c.height);const img=state.photo,iw=img.naturalWidth||img.width,ih=img.naturalHeight||img.height;const sc=Math.min(c.width/iw,c.height/ih),w=iw*sc,h=ih*sc,ox=(c.width-w)/2,oy=(c.height-h)/2;state.photoBox={ox,oy,w,h};x.drawImage(img,ox,oy,w,h);x.strokeStyle="rgba(62,224,195,.45)";for(let i=0;i<=n;i++){x.beginPath();x.moveTo(ox,oy+h*i/n);x.lineTo(ox+w,oy+h*i/n);x.stroke();x.beginPath();x.moveTo(ox+w*i/n,oy);x.lineTo(ox+w*i/n,oy+h);x.stroke()}if(state.pat&&state.pat.length===n*n){for(let gz=0;gz<n;gz++)for(let gx=0;gx<n;gx++){if(!state.pat[gz*n+gx])continue;x.fillStyle="rgba(62,224,195,.28)";x.fillRect(ox+w*gx/n,oy+h*gz/n,w/n,h/n)}}}
function cellStats(data,cw,ch,x0,y0,x1,y1){const lum=[];let sx=0,sy=0,rS=0,gS=0,bS=0,cnt=0;for(let py=y0|0;py<y1;py++)for(let px=x0|0;px<x1;px++){if(px<1||py<1||px>=cw-1||py>=ch-1)continue;const i=(py*cw+px)*4,r=data[i],g=data[i+1],b=data[i+2],a=data[i+3];if(a<20)continue;const L=0.2126*r+0.7152*g+0.0722*b;lum.push(L);rS+=r;gS+=g;bS+=b;cnt++;sx+=0.2126*data[i+4]+0.7152*data[i+5]+0.0722*data[i+6]-L;sy+=0.2126*data[i+cw*4]+0.7152*data[i+cw*4+1]+0.0722*data[i+cw*4+2]-L}if(!cnt)return{avg:255,h:0,sat:0,v:1,ang:0};const col=hsv(rS/cnt,gS/cnt,bS/cnt);let ang=Math.atan2(sy,sx)*180/Math.PI;if(ang<0)ang+=360;return{avg:median(lum),h:col.h,sat:col.s,v:col.v,ang}}
function classify(st,mode,thr){if(mode==="dark"||mode==="bedrock")return st.avg<=thr;if(mode==="deepslate")return st.avg>18&&st.avg<thr+45&&st.sat<0.28&&st.v<0.55;if(mode==="bamboo")return st.h>65&&st.h<165&&st.sat>0.18&&st.v>0.16;if(mode==="clouds")return st.avg>=Math.max(170,240-thr)&&st.sat<0.2;if(st.h>65&&st.h<165&&st.sat>0.25&&st.v>0.2)return"bamboo";if(st.avg>=205&&st.sat<0.16)return"clouds";if(st.avg<=thr)return"dark";if(st.avg>18&&st.avg<115&&st.sat<0.24)return"deepslate";return 0}
function rotBucket(ang){const a=((ang%180)+180)%180;if(a<22.5||a>=157.5)return 0;if(a<67.5)return 1;if(a<112.5)return 2;return 3}
function analyzePhoto(){const c=document.getElementById("pcv");if(!c||!state.photo){const e=document.getElementById("pread");if(e)e.textContent="Upload a photo first.";return}const x=c.getContext("2d"),n=state.gridN||8,box=state.photoBox||(drawPhoto(),state.photoBox),mode=state.pmode||"auto";x.drawImage(state.photo,box.ox,box.oy,box.w,box.h);const data=x.getImageData(0,0,c.width,c.height).data;const stats=[];for(let gz=0;gz<n;gz++)for(let gx=0;gx<n;gx++)stats.push(cellStats(data,c.width,c.height,box.ox+box.w*(gx+.18)/n,box.oy+box.h*(gz+.18)/n,box.ox+box.w*(gx+.82)/n,box.oy+box.h*(gz+.82)/n));let thr=state.thr|0;if(!thr)thr=otsu(stats.map(s=>s.avg|0));state.pat=Array(n*n).fill(0);state.rots=Array(n*n).fill(-1);const counts={dark:0,deepslate:0,bamboo:0,clouds:0,other:0};for(let i=0;i<n*n;i++){const st=stats[i];if(mode==="rotation"){state.rots[i]=rotBucket(st.ang);state.pat[i]=1;continue}const tag=classify(st,mode,thr);if(mode==="auto"){state.pat[i]=tag?1:0;if(tag&&counts[tag]!=null)counts[tag]++;else counts.other++}else{state.pat[i]=tag?1:0;if(tag)counts[mode==="bedrock"?"dark":mode]++;else counts.other++}}drawPhoto();paintGrid();const e=document.getElementById("pread");if(e)e.textContent=mode==="rotation"?"Cell numbers are 0 / 90 / 180 / 270. Java only.":`threshold ${thr}. dark ${counts.dark}, deepslate ${counts.deepslate}, bamboo ${counts.bamboo}, clouds ${counts.clouds}, other ${counts.other}.`}
function paintKnown(){const box=document.getElementById("known");if(!box)return;box.innerHTML=state.known.map((k,i)=>`<div class="cond" style="grid-template-columns:1fr 90px 90px 36px"><select data-i="${i}" data-k="id">${opts(k.id)}</select><input data-i="${i}" data-k="x" type="number" value="${k.x}"><input data-i="${i}" data-k="z" type="number" value="${k.z}"><button class="ghost" data-del="${i}">x</button></div>`).join("");box.querySelectorAll("[data-k]").forEach(el=>el.oninput=()=>{state.known[+el.dataset.i][el.dataset.k]=el.dataset.k==="id"?el.value:+el.value});box.querySelectorAll("[data-del]").forEach(b=>b.onclick=()=>{state.known.splice(+b.dataset.del,1);paintKnown()})}
function paintGrid(){const g=document.getElementById("pg");if(!g)return;const n=state.gridN||8;if(!state.pat||state.pat.length!==n*n)state.pat=Array(n*n).fill(0);if(!state.rots||state.rots.length!==n*n)state.rots=Array(n*n).fill(-1);g.style.gridTemplateColumns=`repeat(${n},22px)`;g.innerHTML=state.pat.map((v,i)=>`<i class="${v?"on":""}" data-i="${i}" style="width:22px;height:22px;font-size:9px;display:flex;align-items:center;justify-content:center">${state.pmode==="rotation"&&state.rots[i]>=0?state.rots[i]:""}</i>`).join("");g.querySelectorAll("i").forEach(el=>el.onclick=()=>{const i=+el.dataset.i;if(state.pmode==="rotation"){state.rots[i]=(state.rots[i]+1)%4;state.pat[i]=1}else state.pat[i]^=1;paintGrid();if(state.photo)drawPhoto()})}
function paintKResults(){const stats=document.getElementById("kstats"),rows=document.getElementById("krows");if(!rows)return;if(stats&&state.stats){const tested=Math.min(state.stats.tested||0,state.stats.total||0),total=state.stats.total||0,pct=total?tested*100/total:0;stats.innerHTML=`<strong>${pct.toFixed(2)}%</strong> ${tested.toLocaleString()} / ${total.toLocaleString()} · hits ${state.stats.matched}`}rows.innerHTML=(state.results||[]).map(r=>`<tr><td>${r.seed}</td></tr>`).join("")}
function runCrack(){stopSearch();if(!state.known.length)return;state.running=true;state.results=[];state.stats={tested:0,matched:0,total:state.seedCount};paintKResults();const n=state.workers,per=Math.ceil(state.seedCount/n);let done=0;const live=Array(n).fill(0),liveMatch=Array(n).fill(0);const src=ENGINE+"\nonmessage=function(ev){var d=ev.data,results=[],matched=0;for(var i=0;i<d.count;i++){var s=((Math.random()*0x100000000)>>>0);if(matchKnown(s,d.known,d.tol)){matched++;results.push({seed:String(s>>>0)});if(results.length>20)results.length=20}if((i&8191)===8191)postMessage({type:'prog',wid:d.wid,tested:i+1,matched:matched,results:null})}postMessage({type:'done',wid:d.wid,tested:d.count,matched:matched,results:results})}";for(let w=0;w<n;w++){const count=Math.max(0,Math.min(per,state.seedCount-w*per));if(!count){done++;continue}const worker=new Worker(URL.createObjectURL(new Blob([src],{type:"text/javascript"})));state.workersRef.push(worker);worker.onmessage=ev=>{const m=ev.data;if(m.results&&m.results.length){const acc=new Map(state.results.map(r=>[r.seed,r]));for(const r of m.results)acc.set(r.seed,r);state.results=[...acc.values()].slice(0,40)}if(typeof m.wid==="number"){live[m.wid]=m.tested||0;liveMatch[m.wid]=m.matched||0}if(m.type==="done"){done++;worker.terminate();if(done>=n)state.running=false}state.stats.tested=live.reduce((a,b)=>a+b,0);state.stats.matched=liveMatch.reduce((a,b)=>a+b,0);if(page==="crack")paintKResults()};worker.postMessage({wid:w,count,known:state.known,tol:state.tol})}}
function searchPattern(){const out=document.getElementById("pout");const n=state.gridN||8,y=state.patY||-64,mode=state.pmode||"auto",be=state.pedition!=="java";if(mode==="rotation"){if(be){out.textContent="Texture rotation search is Java only.";return}if(!state.rots||!state.rots.some(v=>v>=0)){out.textContent="Read a photo in texture rotation mode first.";return}const hits=[];const span=64;for(let ox=-span;ox<=span;ox++){for(let oz=-span;oz<=span;oz++){let ok=1;for(let i=0;i<n*n&&ok;i++){if(state.rots[i]<0)continue;if(texRot(ox+(i%n),y,oz+(i/n|0))!==state.rots[i])ok=0}if(ok)hits.push({x:ox,z:oz});if(hits.length>=8)break}if(hits.length>=8)break}out.textContent=hits.length?("Java texture matches: "+hits.map(h=>h.x+", "+y+", "+h.z).join(" · ")):"No Java texture match in ±64 of 0,0.";return}if(mode==="bedrock"){if(be){out.textContent="Bedrock Edition floor matching is not in this engine.";return}const seed=parseSeed(state.patSeed||"0").seed;if(!state.pat||!state.pat.some(v=>v)){out.textContent="Read a photo first.";return}const hits=[];const span=48;for(let ox=-span;ox<=span;ox++){for(let oz=-span;oz<=span;oz++){let ok=1;for(let i=0;i<n*n&&ok;i++){if(javaBedrockFloor(seed,ox+(i%n),y,oz+(i/n|0))!==!!state.pat[i])ok=0}if(ok)hits.push({x:ox,z:oz});if(hits.length>=8)break}if(hits.length>=8)break}out.textContent=hits.length?("Java floor matches: "+hits.map(h=>h.x+", "+y+", "+h.z).join(" · ")):"No Java floor match.";return}out.textContent="This pickup mode labels the photo for Bedrock and Java. It does not print unique coordinates."}
(function(){const old=render;render=function(){if(page==="photo")renderPhoto();else old()}})();
