const JAVA_SRC=`function i32(n){return n|0}
function javaSlime(worldSeed,x,z){let s=BigInt.asIntN(64,BigInt(worldSeed)+BigInt(i32(i32(x*x)*0x4c1906))+BigInt(i32(x*0x5ac0db))+BigInt(i32(z*z))*0x4307a7n+BigInt(i32(z*0x5f24f)))^0x3ad8025fn;let seed=(s^0x5DEECE66Dn)&((1n<<48n)-1n);while(true){seed=(seed*0x5DEECE66Dn+0xBn)&((1n<<48n)-1n);const bits=seed>>17n;const val=bits%10n;if(bits-val+9n>=0n)return val===0n}}
function stafford(z){z=BigInt.asUintN(64,z);z=BigInt.asUintN(64,(z^(z>>30n))*0xBF58476D1CE4E5B9n);z=BigInt.asUintN(64,(z^(z>>27n))*0x94D049BB133111EBn);return BigInt.asUintN(64,z^(z>>31n))}
function xoroshiro(lo,hi){return{lo:BigInt.asUintN(64,lo),hi:BigInt.asUintN(64,hi),nextLong(){const s0=this.lo,s1=this.hi;const sum=BigInt.asUintN(64,s0+s1);const res=BigInt.asUintN(64,((sum<<17n)|(sum>>47n))+s0);const h=BigInt.asUintN(64,s1^s0);this.lo=BigInt.asUintN(64,((s0<<49n)|(s0>>15n))^h^(h<<21n));this.hi=BigInt.asUintN(64,(h<<28n)|(h>>36n));return res},nextFloat(){return Number(this.nextLong()>>40n)/16777216}}}
function javaBedrockFloor(worldSeed,x,y,z){if(y<=-64)return true;if(y>=-59)return false;const lo=stafford(BigInt.asIntN(64,worldSeed)+0x6A09E667F3BCC909n),hi=stafford(BigInt.asIntN(64,worldSeed)+0x9E3779B97F4A7C15n);let mix=BigInt.asUintN(64,BigInt(i32(x)*3129871)^BigInt(i32(z))*116129781n^BigInt(i32(y)));mix=BigInt.asUintN(64,mix*mix*42317861n+mix*11n)>>16n;const rng=xoroshiro(mix^lo,hi);return rng.nextFloat()<((-59-y)/5)}
function javaNextInt(state,n){while(true){state.s=(state.s*0x5DEECE66Dn+0xBn)&((1n<<48n)-1n);const bits=state.s>>17n;const val=bits%BigInt(n);if(bits-val+BigInt(n)-1n>=0n)return Number(val)}}
function javaVillageNear(seed,x,z,tol){const spacing=34,sep=8,salt=10387312;const rcx=Math.round((x>>4)/spacing),rcz=Math.round((z>>4)/spacing);const tol2=tol*tol;for(let rx=rcx-1;rx<=rcx+1;rx++)for(let rz=rcz-1;rz<=rcz+1;rz++){let raw=BigInt.asIntN(64,BigInt(seed)+BigInt(rx)*341873128712n+BigInt(rz)*132897987541n+BigInt(salt));let st={s:(raw^0x5DEECE66Dn)&((1n<<48n)-1n)};const off=spacing-sep;const cx=rx*spacing+javaNextInt(st,off),cz=rz*spacing+javaNextInt(st,off);const bx=(cx<<4)+8,bz=(cz<<4)+8,dx=bx-x,dz=bz-z;if(dx*dx+dz*dz<=tol2)return true}return false}
function javaOk(seed,slimes,vils,tol,pat,n,y,ox,oz){if(vils&&vils.length){for(let i=0;i<vils.length;i++){if(!javaVillageNear(seed,vils[i].x,vils[i].z,tol))return false}}if(slimes&&slimes.length){for(let i=0;i<slimes.length;i++){if(!javaSlime(seed,slimes[i].cx,slimes[i].cz))return false}}if(pat&&pat.length){for(let i=0;i<pat.length;i++){if(javaBedrockFloor(seed,ox+(i%n),y,oz+(i/n|0))!==!!pat[i])return false}}return true}`;
function runJavaCrack(){stopSearch();if(!(state.jvillages&&state.jvillages.length)&&!(state.slimes&&state.slimes.length))return;state.running=true;state.results=[];state.stats={tested:0,matched:0,total:state.seedCount};paintKResults();const n=state.workers,per=Math.ceil(state.seedCount/n);let done=0;const live=Array(n).fill(0),liveMatch=Array(n).fill(0);const src=JAVA_SRC+"\nonmessage=function(ev){var d=ev.data,results=[],matched=0;for(var i=0;i<d.count;i++){var s=BigInt.asIntN(32,BigInt((Math.random()*0x100000000)>>>0));if(javaOk(s,d.slimes,d.vils,d.tol,d.pat,d.n,d.y,d.ox,d.oz)){matched++;results.push({seed:String(s)});if(results.length>20)results.length=20}if((i&4095)===4095)postMessage({type:'prog',wid:d.wid,tested:i+1,matched:matched,results:null})}postMessage({type:'done',wid:d.wid,tested:d.count,matched:matched,results:results})}";
for(let w=0;w<n;w++){const count=Math.max(0,Math.min(per,state.seedCount-w*per));if(!count){done++;continue}const worker=new Worker(URL.createObjectURL(new Blob([src],{type:"text/javascript"})));state.workersRef.push(worker);worker.onmessage=ev=>{const m=ev.data;if(m.results&&m.results.length){const acc=new Map(state.results.map(r=>[r.seed,r]));for(const r of m.results)acc.set(r.seed,r);state.results=[...acc.values()].slice(0,40)}if(typeof m.wid==="number"){live[m.wid]=m.tested||0;liveMatch[m.wid]=m.matched||0}if(m.type==="done"){done++;worker.terminate();if(done>=n)state.running=false}state.stats.tested=live.reduce((a,b)=>a+b,0);state.stats.matched=liveMatch.reduce((a,b)=>a+b,0);if(page==="crack")paintKResults()};worker.postMessage({wid:w,count,slimes:state.slimes||[],vils:state.jvillages||[],tol:state.jtol||128,pat:null,n:8,y:-64,ox:0,oz:0})}}
