window.JAVA_SRC=`function i32(n){return n|0}
function javaSlime(worldSeed,x,z){let s=BigInt.asIntN(64,BigInt(worldSeed)+BigInt(i32(i32(x*x)*0x4c1906))+BigInt(i32(x*0x5ac0db))+BigInt(i32(z*z))*0x4307a7n+BigInt(i32(z*0x5f24f)))^0x3ad8025fn;let seed=(s^0x5DEECE66Dn)&((1n<<48n)-1n);while(true){seed=(seed*0x5DEECE66Dn+0xBn)&((1n<<48n)-1n);const bits=seed>>17n;const val=bits%10n;if(bits-val+9n>=0n)return val===0n}}
function javaNextInt(state,n){while(true){state.s=(state.s*0x5DEECE66Dn+0xBn)&((1n<<48n)-1n);const bits=state.s>>17n;const val=bits%BigInt(n);if(bits-val+BigInt(n)-1n>=0n)return Number(val)}}
function javaVillageNear(seed,x,z,tol){const spacing=34,sep=8,salt=10387312;const rcx=Math.round((x>>4)/spacing),rcz=Math.round((z>>4)/spacing);const tol2=tol*tol;for(let rx=rcx-1;rx<=rcx+1;rx++)for(let rz=rcz-1;rz<=rcz+1;rz++){let raw=BigInt.asIntN(64,BigInt(seed)+BigInt(rx)*341873128712n+BigInt(rz)*132897987541n+BigInt(salt));let st={s:(raw^0x5DEECE66Dn)&((1n<<48n)-1n)};const off=spacing-sep;const cx=rx*spacing+javaNextInt(st,off),cz=rz*spacing+javaNextInt(st,off);const bx=(cx<<4)+8,bz=(cz<<4)+8,dx=bx-x,dz=bz-z;if(dx*dx+dz*dz<=tol2)return true}return false}
function javaOk(seed,slimes,vils,tol,pat,n,y,ox,oz){if(vils&&vils.length){for(let i=0;i<vils.length;i++){if(!javaVillageNear(seed,vils[i].x,vils[i].z,tol))return false}}if(slimes&&slimes.length){for(let i=0;i<slimes.length;i++){if(!javaSlime(seed,slimes[i].cx,slimes[i].cz))return false}}return true}`;
function compact(n){n=n||0;if(n>=1e9)return(n/1e9).toFixed(2)+"b";if(n>=1e6)return(n/1e6).toFixed(2)+"m";if(n>=1e3)return(n/1e3).toFixed(1)+"k";return String(Math.round(n))}
function etaText(tested,total,sps){if(!sps||tested>=total)return state.running?"finishing":"done";const s=(total-tested)/sps;if(s>3600)return(s/3600).toFixed(1)+"h";if(s>60)return(s/60).toFixed(1)+"m";return Math.max(1,Math.ceil(s))+"s"}
function paintResults(){const stats=document.getElementById("stats"),rows=document.getElementById("rows");if(!stats||!rows)return;if(state.stats){const tested=Math.min(state.stats.tested||0,state.stats.total||0),total=state.stats.total||0,pct=total?tested*100/total:0,sps=state.stats.sps||0;stats.innerHTML=`<div class="card"><strong>Progress ${pct.toFixed(2)}%</strong><div class="bar"><i style="width:${pct}%"></i><span>${compact(tested)} / ${compact(total)}</span></div><p class="note">${tested.toLocaleString()} of ${total.toLocaleString()} · ${compact(sps)}/s · ETA ${etaText(tested,total,sps)} · hits ${state.stats.matched||0} · ${state.random?"random":"sequential"}</p></div>`}rows.innerHTML=state.results.map((r,i)=>`<tr data-i="${i}"><td>${i+1}</td><td>${r.seed}</td><td class="match">${(r.match||99).toFixed?r.match.toFixed(1):99}%</td></tr>`).join("");rows.querySelectorAll("tr").forEach(tr=>tr.onclick=()=>{const r=state.results[+tr.dataset.i];document.getElementById("detail").innerHTML=`<h3>${r.seed}</h3>${(r.hits||[]).map(h=>`<p>${h.label||h.name} — ${Math.round(h.distance)}m (${h.x}, ${h.z})</p>`).join("")}<button onclick="navigator.clipboard.writeText('${r.seed}')">Copy</button>`})}
function paintKResults(){const stats=document.getElementById("kstats"),rows=document.getElementById("krows");if(!rows)return;if(stats&&state.stats){const tested=Math.min(state.stats.tested||0,state.stats.total||0),total=state.stats.total||0,pct=total?tested*100/total:0,sps=state.stats.sps||0;stats.innerHTML=`<div class="card"><strong>${pct.toFixed(2)}%</strong><div class="bar"><i style="width:${pct}%"></i><span>${compact(tested)} / ${compact(total)}</span></div><p class="note">${tested.toLocaleString()} of ${total.toLocaleString()} · ${compact(sps)}/s · ETA ${etaText(tested,total,sps)} · hits ${state.stats.matched||0}</p></div>`}rows.innerHTML=(state.results||[]).map(r=>`<tr><td>${r.seed}</td></tr>`).join("")}
const _renderSearch=renderSearch;
renderSearch=function(){_renderSearch();const row=document.querySelector("#sc")&&document.querySelector("#sc").closest(".card");if(row&&!document.getElementById("quickN")){const q=document.createElement("div");q.className="row";q.id="quickN";q.innerHTML=`<button class="secondary" data-n="100000">100k</button><button class="secondary" data-n="1000000">1m</button><button class="secondary" data-n="2000000">2m</button><button class="secondary" data-n="10000000">10m</button><button class="secondary" data-n="100000000">100m</button><label class="field"><input id="r99" type="checkbox" ${state.stop99?"checked":""}> stop at 99%</label>`;row.appendChild(q);q.querySelectorAll("[data-n]").forEach(b=>b.onclick=()=>{state.seedCount=+b.dataset.n;document.getElementById("sc").value=state.seedCount})}const go=document.getElementById("go");if(go)go.onclick=()=>{state.seedCount=Math.max(1,Math.min(1e9,+document.getElementById("sc").value||1));state.workers=Math.max(1,Math.min(16,+document.getElementById("wk").value||1));state.random=document.getElementById("rnd").checked;const r99=document.getElementById("r99");if(r99)state.stop99=r99.checked;runSearch()}};
const _runSearch=runSearch;
runSearch=function(){const t0=performance.now();_runSearch();const tick=()=>{if(!state.running)return;if(state.stats)state.stats.sps=state.stats.tested*1000/Math.max(1,performance.now()-t0);if(page==="search")paintResults();requestAnimationFrame(tick)};requestAnimationFrame(tick)};
function applyTheme(name){document.documentElement.setAttribute("data-theme",name);try{localStorage.setItem("seed-theme",name)}catch(e){}}
renderSettings=function(){view.innerHTML=`<h2>Settings</h2><div class="card"><h3>Theme</h3><div class="row"><button data-th="night">Night</button><button data-th="cherry">Cherry blossom</button><button data-th="space">Space</button><button data-th="car">Car night</button><button data-th="ocean">Ocean</button><button data-th="nether">Nether</button></div></div>`;view.querySelectorAll("[data-th]").forEach(b=>b.onclick=()=>applyTheme(b.dataset.th))};
try{const th=localStorage.getItem("seed-theme");if(th)applyTheme(th)}catch(e){}
function runJavaCrack(){stopSearch();const vils=state.jvillages||[];const slimes=state.slimes||[];if(!vils.length&&!slimes.length){if(document.getElementById("kstats"))document.getElementById("kstats").innerHTML="<p class='note'>Add a Java village X/Z first.</p>";return}state.running=true;state.results=[];state.stats={tested:0,matched:0,sps:0,total:state.seedCount};paintKResults();const n=state.workers,per=Math.ceil(state.seedCount/n),t0=performance.now();let done=0;const live=Array(n).fill(0),liveMatch=Array(n).fill(0);const src=(window.JAVA_SRC||"")+"\nonmessage=function(ev){var d=ev.data,results=[],matched=0;for(var i=0;i<d.count;i++){var s=BigInt.asIntN(32,BigInt((Math.random()*0x100000000)>>>0));if(javaOk(s,d.slimes,d.vils,d.tol,d.pat,d.n,d.y,d.ox,d.oz)){matched++;results.push({seed:String(s)});if(results.length>20)results.length=20}if((i&4095)===4095)postMessage({type:'prog',wid:d.wid,tested:i+1,matched:matched,results:null})}postMessage({type:'done',wid:d.wid,tested:d.count,matched:matched,results:results})}";for(let w=0;w<n;w++){const count=Math.max(0,Math.min(per,state.seedCount-w*per));if(!count){done++;continue}const worker=new Worker(URL.createObjectURL(new Blob([src],{type:"text/javascript"})));state.workersRef.push(worker);worker.onmessage=ev=>{const m=ev.data;if(m.results&&m.results.length){const acc=new Map(state.results.map(r=>[r.seed,r]));for(const r of m.results)acc.set(r.seed,r);state.results=[...acc.values()].slice(0,40)}if(typeof m.wid==="number"){live[m.wid]=m.tested||0;liveMatch[m.wid]=m.matched||0}if(m.type==="done"){done++;worker.terminate();if(done>=n)state.running=false}state.stats.tested=live.reduce((a,b)=>a+b,0);state.stats.matched=liveMatch.reduce((a,b)=>a+b,0);state.stats.sps=state.stats.tested*1000/Math.max(1,performance.now()-t0);if(page==="crack")paintKResults()};worker.postMessage({wid:w,count,slimes:slimes,vils:vils,tol:state.jtol||128,pat:null,n:8,y:-64,ox:0,oz:0})}}
